### ISSUE TITLE
question: NVDA 2019.3 and compatible seika mini display driverissue

### ISSUE THREAD

**Issue by khsbory** [accessolutions/seikamini-nvda#1]
Hello, my name is Hyongsop Kim and NVDA with seika mini user.
I used seika mini with NVDA very well until NVDA 2019.2 version.
But now NVDA is updated to 2019.3 based on python 3 and it is not possible to use seika mini addon.
So I want to ask you that when will be released seika mini NVDA driver compatible with NVDA 2019.3 version?
Thank you.

**Comment by lijianwei2019** [comment]
[](url)https://github.com/nvaccess/nvda/pull/9479

**Comment by JulienCochuyt** [comment]
Dear @khsbory,

This add-on is now compatible with NVDA from 2012.2 to 2019.3.1
Download link: https://github.com/accessolutions/seikamini-nvda/releases/download/3.2.2019.3.1/seikamini-3.2.2019.3.1.nvda-addon

We are looking forward your feedback on this release.
