### ISSUE TITLE
[](url)Add driver for seika notetaker braille display #9479

### ISSUE THREAD

**Issue by lijianwei2019** [accessolutions/seikamini-nvda#2]
[](url)https://github.com/nvaccess/nvda/pull/9479

_Originally posted by @lijianwei2019 in https://github.com/accessolutions/seikamini-nvda/issues/1#issuecomment-586557281_

**Comment by JulienCochuyt** [comment]
Dear @lijianwei2019,

This add-on is now compatible with NVDA from 2012.2 to 2019.3.1
Download link: https://github.com/accessolutions/seikamini-nvda/releases/download/3.2.2019.3.1/seikamini-3.2.2019.3.1.nvda-addon

We are looking forward your feedback on this release.
